package-lock.json
package.json
src/pages/_app.js

This removes hardcoded Google Analytics tracking.

Remove Google Analytics

---

src/components/Editor/Editor.tsx
src/components/Editor/EditorDropdown.tsx
src/components/Editor/EditorSidebar.tsx
src/components/Modals/ConfirmModal.tsx
src/components/Modals/ImportURLModal.tsx
src/components/Modals/index.tsx
src/components/common/Dropdown.tsx
src/components/common/index.ts
src/services/editor.service.ts
src/services/specification.service.ts

- add dropdown in the editor:
- functionality to download given AsyncAPI document from URL
- functionality to load given AsyncAPI document from file system
After clicking to appropriate item, the modal with the form appears.
See also #80

chore: add editor dropdown

---

package.json

PR adds two missed scripts `lint` and `generate:assets` needed by our workflows - at the moment every bump of global workflows in repo is broken, like this https://github.com/asyncapi/studio/pull/103

ci: add missed scripts for workflows

---

src/components/Editor/EditorDropdown.tsx
src/services/editor.service.ts

Add new functionalities to the editor dropdown:
- possibility to convert JSON <-> YAML
- possibility to save given AsyncAPI doc to file
- possibility to save given AsyncAPI doc to file after converting JSON <-> YAML
See also #80

feat: add new functionalities to the editor dropdown

---

.eslintignore
.eslintrc
package-lock.json
package.json
src/App.tsx
src/components/Editor/EditorDropdown.tsx
src/components/Editor/MonacoWrapper.tsx
src/components/Modals/ConvertModal.tsx
src/components/Modals/ConvertToLatestModal.tsx
src/components/Navigation.tsx
src/components/Terminal/TerminalTabs.tsx
src/components/common/Dropdown.tsx
src/helpers/debounce.ts
src/index.tsx
src/services/editor.service.ts
src/services/monaco.service.ts
src/services/navigation.service.ts
src/services/specification.service.ts
src/services/tests/format.service.test.ts
src/services/tests/specification.service.test.ts

- Add eslint config (with needed plugins)
- Fix errors throw by eslint
Fixes #109

chore: add eslint

---

.gitpod.yml
README.md

This PR adds Gitpod support with a .gitpod.yml file (which automates the dev environment) and updates the README.md.

chore: add gitpod support

---

.dockerignore
Dockerfile
README.md
package-lock.json
package.json
src/services/specification.service.ts

Fixes #30
Took some inspiration from https://github.com/asyncapi/server-api/pull/24
🛠 with ❤ at Siemens

feat: create Docker image

---

src/components/Modals/Settings/SettingsModal.tsx
src/components/Sidebar.tsx

-  Added tooltip to `sidebar.tsx`
-  Added tooltip to `settings.tsx`
Fixes #242

fix: add titles to sidebar's nodes

---

public/_redirects

chore: add playground redirects

---

Dockerfile

- Fixed typo. `occurences` -> `occurrences`

chore: fix typo in Dockerfile

---

.asyncapi-tool.yaml

- add `.asyncapi-tool.yaml` file to show the Studio as tool in the `asyncapi.com/tools` dashboard.
cc @derberg

chore: add .asyncapi-tool.yaml file

---

src/components/Editor/MonacoWrapper.tsx
src/services/app.service.ts
src/services/editor.service.tsx
src/services/index.ts
src/services/parser.service.ts
src/state/files.state.ts

Fix handling of url/base64 query parameters.
Fixes #530

fix: handling of url/base64 query parameters

---

.github/workflows/add-scope-to-bet.yml

fix: adding issues to scope not working in orgs

---

.github/workflows/lint-pr-adr.yml

Fixing the CI issue https://github.com/Amzani/shapeup/pull/40

fix: adr linting

---

apps/studio/src/components/Navigation.tsx

This PR does not solve https://github.com/asyncapi/studio/issues/800 but at least it does not break the entire website.
Fixes https://github.com/asyncapi/studio/issues/799

fix: broken navigation with v3 input 

---

.github/workflows/issues-metrics.yml

Related to https://github.com/asyncapi/studio/issues/805

ci: add issue metrics action

---

apps/studio/.sonarcloud.properties

With the transition to spec 3.0 we will have some duplicated code.

ci: add sonarcloud exclusions

---

.sonarcloud.properties
apps/studio/.sonarcloud.properties

https://github.com/asyncapi/studio/pull/821 didn't work. Trying to move the sonarcloud config to root.

ci: move sonarcloud.properties

---

.github/workflows/issues-metrics.yml

ci: fix issue metrics action

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/pitch.yml
.github/pull_request_template.md

chore: add missing issues templates

---

apps/studio/src/state/files.state.ts

Related to: https://asyncapi.slack.com/archives/C34F2JV0U/p1701685416306489?thread_ts=1701618246.696289&cid=C34F2JV0U

fix: default spec 3.0.0 doc

---

.github/workflows/release.yml
package.json

ci: add NPM script for publishing to npm

---

apps/studio/src/components/Modals/ConfirmModal.tsx

fix: modal size

---

.changeset/moody-rabbits-love.md
apps/studio-next/package.json
apps/studio/package.json
package-lock.json
package.json

- Bump dependencies that were not merged automatically.
- move `studio-next` dependencies to it's package.json

bump and move dependencies

---

.sonarcloud.properties
apps/design-system/src/components/DropdownMenu.stories.tsx
apps/design-system/src/components/SlideOver.stories.tsx

Fixes: https://github.com/asyncapi/studio/issues/991

fix: padding in the design system

---

.changeset/three-yaks-explode.md

- create a release for #990 and #1031

Release a patch version

---

apps/design-system/src/components/VisualJsonSchemaEditor.stories.tsx
apps/studio-next/src/components/Editor/Editor.tsx

Fixes the linting errors in studio-next.
Fixes #1029

fix linting errors

---

apps/studio/Dockerfile

Upgrade nginx to version 1.25.5-alpine

---

.changeset/lazy-deers-work.md
apps/studio/package.json
package-lock.json

- I fixed the issue in the dependency (`@asyncapi/react-component` package): https://github.com/asyncapi/asyncapi-react/issues/993
- Now I'm upgrading that dependency
Fixes #1066

fix: security schemas by upgrading the dependency

---

CODEOWNERS

This PR adds @Shurtu-gal as a code owner.

chore: add @Shurtu-gal as code owner

---

.changeset/neat-nails-shop.md
apps/design-system/.storybook/main.ts
apps/studio/package.json

- Need to include next.config.js for use in cli.
https://github.com/asyncapi/cli/pull/1695
Fixes: #1159
Fixes https://github.com/asyncapi/cli/issues/1718

fix: include next.config.js

---

.changeset/orange-ladybugs-sparkle.md
apps/studio/package.json
pnpm-lock.yaml

#1161 
https://github.com/asyncapi/asyncapi-react/issues/1117

fix: upgrade asyncapi-react to latest version

---

.github/workflows/lint-pr-adr.yml

- Anchoring to safe commit as in https://github.com/asyncapi/website/blob/master/.github/workflows/validate-case-studies-structures.yaml#L20
Ref: https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised

ci: anchor action to commit

---

apps/studio/cypress.config.ts
apps/studio/cypress/e2e/studio-ui.spec.cy.ts
apps/studio/src/components/Editor/ConvertDropdown.tsx
apps/studio/src/components/Editor/EditorSidebar.tsx
apps/studio/src/components/Editor/GenerateDropdown.tsx
apps/studio/src/components/Editor/ImportDropdown.tsx
apps/studio/src/components/Editor/SaveDropdown.tsx
apps/studio/src/components/Modals/ConfirmModal.tsx
apps/studio/src/components/common/Dropdown.tsx
apps/studio/src/services/server-api.service.ts

- Categorized and added options from the main dropdown into different dropdowns in the main bar over the editor
- Added icons which seemed most suitable according to the category
Related #1104

feat: Added dropdowns in main menu bar over the Editor

---

.changeset/eighty-peas-cry.md

Added changeset for the PR #1194.

chore: add changeset.
