src/components/Content.tsx, src/components/Navigation.tsx, src/components/Sidebar.tsx, src/components/index.ts, src/index.tsx, src/main.css, src/services/index.ts, src/services/navigation.service.ts, src/studio.tsx
- add `Navigation` component next to editor and template.
- add `NavigationService` with `scrollTo` functions - based on `hashchange` event.
- add `Sidebar` component with the ability to hide the given block - navigation, editor or template.
- add "stretching" functionality - navigation, editor, template can be stretched to the given horizontal size.
- update relevant component like `Content` and main file.
- add `main.css` file with styles for "stretching" functionality.
See also https://github.com/asyncapi/studio/issues/80
=> chore: add navigation

package-lock.json, package.json, src/components/Editor/EditorDropdown.tsx, src/components/Modals/ConvertModal.tsx, src/components/Modals/ConverterModal.tsx, src/components/Modals/ImportBase64Modal.tsx, src/components/Modals/index.tsx, src/components/Terminal/ProblemsTab.tsx, src/services/editor.service.ts, src/services/format.service.ts, src/services/monaco.service.ts, src/services/specification.service.ts, src/services/tests/format.service.test.ts, src/services/tests/specification.service.test.ts
- Add convert functionality - add new node in the editor dropdown - `convert`
- Add functionality to load AsyncAPI doc from `base64` - new node in the editor dropdown
- Add relevant unit tests
See also #80
=> chore: add convert functionality

src/services/json-schema.draft-07.ts, src/services/monaco.service.ts
Use reference to the json-schema draft-07 in the Monaco editor.
See more https://github.com/asyncapi/spec-json-schemas/pull/119
=> fix: use reference to the json-schema draft-07 in monaco editor

public/_redirects
We're shutting down [editor.asyncapi.org](http://editor.asyncapi.org) but we don't want to show a 404 to users but instead give them the alternative to use Studio. For that purpose, I want to redirect to Studio here.
If you navigate to [editor.asyncapi.org](http://editor.asyncapi.org), you'll notice that the redirect is already in place. This is because I've edited the code in its machine to do the redirect.
Yes, it's too Monday for me 😄 However, this redirect is happening because I'm paying for a DigitalOcean droplet (machine) to handle it. I want to stop paying for this stupid redirect so I'll change DNS in Netlify to point to Studio. It's not possible to do redirects with DNS and therefore I want the code here to be ready for when the new DNS is in place.
Bye bye AsyncAPI 1.0.0 Editor, …
=> chore: redirect editor.asyncapi.org to studio.asyncapi.com

package-lock.json, package.json
Auto bumping script doesn't work -> https://github.com/asyncapi/asyncapi-react/runs/4700884362?check_suite_focus=true so I bump that dep manually.
Resolves https://github.com/asyncapi/studio/issues/221
=> fix: update react-component to next-27 version

package-lock.json, package.json, src/services/specification.service.ts
Add support for avro and openapi formats.
Why now? Because it is the first time when someone used `avro` schema in the Studio and got an error.... - #237  
The issue mentions that locally it works, but on https://studio.asyncapi.com it does not. This is because of how webpack works in production mode and in development mode. In development mode webpack "sees" all the packages that we use in all parts of the studio and for example `react-component` underneath "adds" support for avro and openapi. Due to the fact that Studio uses a smaller version of react-component without parser (parser is used in studio, so it doesn't need it), after building the application, where webpack "removes" any unused code, support for `avro` and `openapi` is forgotten, so we have to add support …
=> fix: add support for avro and openapi formats

src/examples/index.tsx
- Fixed Gitter spelling typo in the `src/examples/index.tsx`
**Before**
**After**
=> fix: gitter spelling

Dockerfile, README.md, public/index.html, src/components/Toolbar.tsx, src/index.tsx
See the related issue for context.
This PR introduces the following changes:
- Sets `PUBLIC_URL` to a placeholder value during Docker build so `create-react-app` injects the placeholder value in generated assets (see https://create-react-app.dev/docs/advanced-configuration/ and https://create-react-app.dev/docs/deployment/#building-for-relative-paths)
- When the container is started replaces the placeholder value by the configured base URL. If no base URL is configured it will assume being served from root.
- Adapt some places where the `PUBLIC_URL` variable has not been used up to now (see https://create-react-app.dev/docs/using-the-public-folder/) 
Closes #249
=> feat: add support for configuring the base URL

package-lock.json, package.json, src/services/specification.service.ts, src/services/tests/specification.service.test.ts
- update `@asyncapi/converter` and `@asyncapi/react-component` to the latest version
- fix failing tests due to fact that `@asyncapi/converter` now handles the JSON spec 🚀 
- fix build of docker image, move `generate:template-parameters` script from `postinstall` to the `build` hook.
Fixes https://github.com/asyncapi/studio/pull/267
Fixes https://github.com/asyncapi/studio/pull/268
Fixes https://github.com/asyncapi/studio/pull/269
Fixes https://github.com/asyncapi/studio/pull/270
=> fix: failing tests for newer versions of the converter

CODEOWNERS
Remove `github-bot` from codeowners.
=> chore: remove github-bot from codeowners

src/components/Modals/ConvertToLatestModal.tsx
- ``` ConvertToLatesModal ``` takes the latest version of AsyncAPI as the default value
Case shown in Screenshot- When the AsyncApi version is set to 1.0.0
Fixes #391
=> fix: point to the latest version in ConvertToLatestModal

craco.config.js
This PR addresses error
```
Error: error:0308010C:digital envelope routines::unsupported
```
when starting AsyncAPI Studio with Node.js v17+.
TL;DR
webpack's hashing algorithm defaults to 'md4', which is deprecated in OpenSSL 3.0 used by Node.js v17+, so it's force-changed to 'sha256'.
The origin of the error is
```
This error is because node.js 17 uses OpenSSL3, which has changed code for
initialization context of md family (including md4), and this is a breaking
change.
```
https://itsmycode.com/error-digital-envelope-routines-unsupported *
A quick workaround for this error would be to specify `NODE_OPTIONS=--openssl-legacy-provider` in `package.json`
```
"start": "cross-env DISABLE_ESLINT_PLUGIN=true NODE_OPTIONS=--openssl-legacy-provider craco start",
```
or alternatively, to set an …
=> fix: force 'crypto.createHash()' to use SHA-256 (#360)

package-lock.json, package.json, src/components/Content.tsx, src/components/Modals/NewFileModal.tsx, src/components/Sidebar.tsx, src/services/converter.service.ts, src/services/parser.service.ts, src/services/settings.service.ts, src/state/app.state.ts, src/state/documents.state.ts, src/state/files.state.ts, src/state/index.state.ts, src/state/panels.state.ts, src/state/settings.state.ts
- start using `zustand` library for state management
- now, new state "doesn't" work, it means that old state and new state coexist in one source code - I don't wanna make huge PR with everything so I split code to few separate PRs.
- update (in this PR) two components with new state management
- old state management (based on proxies) will be removed in the next PR, where will be also update of components with new state 
That PR is a part of refactoring of the Studio to support multiple files.
=> refactor: simplify state management, part 1

src/components/Visualiser/Controls.tsx, src/components/Visualiser/FlowDiagram.tsx, src/components/Visualiser/utils/node-calculator.ts
I found some weird bug: if we wanna move some block in visualiser, then in some cases it doesn't work and it can be possible to see "jumping" of the blocks between renders - from initial position to the destination. That PR fix that. Problem probably occurred through bumping the `react-flow-renderer` dep to the v11 version.
=> fix: possibility of moving blocks in visualiser

src/components/Modals/NewFileModal.tsx, src/examples/ibmmq.yml, src/examples/index.tsx
Adds a template for a basic IBM MQ specification to studio. This template is based on the example from our documentation.
I've also taken the opportunity to fix a typo and to update the MQTT template description as this was previously a copy of the HTTP description.
=> feat: add IBM MQ template

src/services/app.service.ts
- The error message clearly points that it doesn't find a parent `NiceModal.Provider`
```
Uncaught (in promise) Error: No dispatch method detected, did you embed your app with NiceModal.Provider?
at m (index.tsx:104:9)
at _ (index.tsx:225:3)
at i.<anonymous> (app.service.ts:36:7)
at f (regeneratorRuntime.js:44:17)
at Generator.<anonymous> (regeneratorRuntime.js:125:22)
at Generator.next (regeneratorRuntime.js:69:21)
at r (asyncToGenerator.js:3:20)
at s (asyncToGenerator.js:22:9)
```
- the issue was we were having the `show(RedirectModal)` in the `onInit` method, which was called in `createService` method in `/src/services/index.tsx` which was further called inside the `boostrap` method in the `/src/index.tsx`
- reverse stack trace from …
=> fix: redirectFrom query parameter not leading to the opening of a Modal.

CODEOWNERS
I'd love to invite @KhudaDad414 to become a code owner of this repo. Since the rest of the code owners are not very active lately and we want to move the project forward with the new Studio vision and plans: #634. He's already a TSC member so I figured he was the best candidate for now.
=> chore: add Khuda as code owner

apps/studio/package.json, package-lock.json
Replaces https://github.com/asyncapi/studio/pull/572
This PR updates **@asyncapi/parser** to v2 and uses the recently released custom schema parsers.
Note: this PR does not change Studio to start using the new Parser-API but keeps using the old wrapper `const oldDocument = convertToOldAPI(document);`.
https://github.com/asyncapi/parser-js/issues/585
=> fix: update parser-js to v2

apps/studio/Dockerfile, apps/studio/package.json, package.json
- this PR updates the Dockerfile so we can generate a docker image for the release process.
resolves https://github.com/asyncapi/studio/actions/runs/5343506807/jobs/9686791298
=> fix: update Dockerfile to handle monorepo

doc/adr/0002-use-changesets-for-publishing-and-versioning.md
Proposal to use changeset instead of semantic-release for versioning and publising packages to GitHub.
=> chore: [ADR-002] use changesets to manage release

.github/workflows/add-scope-to-bet.yml, .github/workflows/lint-pr-adr.yml
…HUB_TOKEN
Fixes https://github.com/asyncapi/studio/issues/731
=> fix: some actions should have secrets.GH_TOKEN

doc/adr/0004-use-radix-ui.md
=> chore: [ADR-0004] use RadixUI

apps/studio/src/components/Editor/EditorDropdown.tsx, apps/studio/src/services/editor.service.tsx
- I have added an accept attribute for better user experience by showing the files which are supported( currently JSON and YAML).
- Also there is a checker in import file which compares the MIME type as it cannot be handled in HTML.
Fixes #623
=> fix: handle unexpected file formats

apps/studio/package.json, package-lock.json
This PR updates the `@asyncapi/parser` package to the latest version of `next-major-spec` branch so it enables (really) the validation for AsyncAPI v3 documents.
cc @Amzani
=> feat: update Parser-JS to v2.1.0-next-major-spec.5 so it really enables v3 validation

apps/studio/src/examples/tutorials/invalid.yml
- Updated the old link to new one in the `Invalid Example` template in the `New file` section.
Fixes #834
=> fix: update old broken link to new one

CODEOWNERS
Hey Folks, I humbly suggest @Amzani as a code owner of this repo to support the new studio roadmap and mentor current contributors.
- Driving the new studio enhancements as a product manager (e.g [issues](https://github.com/asyncapi/studio/issues?q=+is%3Aissue+project%3Aasyncapi%2F16+author%3AAmzani+) / [shapeIt dashboard](https://shapeit.app/projects/org/asyncapi/16/cycles/09a49498) / [planning meetings](https://www.youtube.com/watch?v=mAISwYCZa2I&ab_channel=AsyncAPI))
- Implementing [ShapeUp methodology](https://github.com/asyncapi/studio/issues/659) as a way to drive new studio enhancement 
- Added Architectural Decision Records (ADR) [process](https://github.com/asyncapi/studio/issues/663)
- Added [spec 3.0 validation support](https://github.com/asyncapi/studio/pull/747)
- Active …
=> chore: Add Amzani as a code owner

doc/adr/0005-use-tailwind-in-design-system.md
I purpose we support styling components in design system with tailwind css.
=> [ADR-0005] support component styling with tailwind css in design system

apps/studio/src/components/Content.tsx, apps/studio/src/components/Modals/Settings/SettingsModal.tsx, apps/studio/src/components/Sidebar.tsx, apps/studio/src/components/Terminal/TerminalTabs.tsx, apps/studio/src/services/specification.service.ts, apps/studio/src/state/files.state.ts, apps/studio/src/state/settings.state.ts
- Make v3 as the default
- When loading V3 is default
Fixes #832
=> chore: make v3 default

apps/studio/src/examples/tutorials/invalid.yml
making sure invalid example match the one mentioned in tutorial 
https://v3.asyncapi.com/docs/tutorials/studio-document-validation
marked as `fix` as I kinda assume it will be automatically released once I do it
=> fix: update official invalid example to match tutorial

CODEOWNERS
I suggest @princerajpoot20 as a code owner for the design system `apps/design-system/` and ui `packages/ui/` as he did major contribution to build the new components, and he is committed to support new studio vision and plans #634.
- https://github.com/asyncapi/studio/pull/708
- https://github.com/asyncapi/studio/pull/710
- https://github.com/asyncapi/studio/pull/711
- https://github.com/asyncapi/studio/pull/718
- https://github.com/asyncapi/studio/pull/792
- https://github.com/asyncapi/studio/pull/808
In addition to committing to this repos he is also reviewing the work of others (e.g https://github.com/asyncapi/studio/pull/784 / https://github.com/asyncapi/studio/pull/773)
=> chore: add princerajpoot20 as code owner for ds and ui

CODEOWNERS
I'm removing myself as a code owner. I don't really have time to review or write code anymore. However, I'll still be participating in some discussions. The repo is now on good hands so no need to keep myself here.
I'm also taking the opportunity to remove @boyney123 and @mcturco as they haven't been active in the repo for more than a year now so I think it's safe to say they're not maintainers either. Challenge this decision if you think I'm wrong, of course. Happy to revert it if needed.
=> chore: removing myself as maintainer

apps/studio/src/components/Modals/ConfirmNewFileModal.tsx, apps/studio/src/components/Modals/index.tsx, apps/studio/src/components/Sidebar.tsx
- The feature creates a modal prompt before creating a new file to prevent user from loosing his data
- Old Behaviour
https://github.com/asyncapi/studio/assets/69006513/d7945641-2319-4de4-af88-b4755da8762b
- Current Behaviour
https://github.com/asyncapi/studio/assets/69006513/8529183a-3d15-440d-9124-d885994d84ec
Resolves: #724
=> Feat: Added confirmation to create new file

apps/studio-next/package.json, apps/studio-next/src/app/page.tsx, apps/studio-next/src/components/Editor/CodeMirror.tsx, apps/studio-next/src/components/Editor/Editor.tsx, apps/studio-next/src/state/files.state.ts, package-lock.json, package.json
- Add editor to the studio-next in next.js
- Using code mirror instead of Monaco
- Is a minimal editor with file state and local storage baked into it 
- Use `esc + tab` for the normal tab and just `tab` if you want in the editor.
Fixes #684
=> feat: add editor in next.js

doc/adr/0007-use-nextjs.md
Following the discussion in #661 this PR makes it official to use Next.js
fixes #1063
=> [ADR-0006] Use Next.js framework

apps/studio/src/components/Toolbar.tsx
- Github icon in the toolbar rightly redirects to Asyncapi Studio Repo. 
- Updated url as well as title.
=> Fixed Issue #1100 about Github link 

apps/design-system/src/components/DropdownMenu.stories.tsx, apps/design-system/src/styles/tailwind.output.css, packages/ui/components/DropdownMenu.tsx, packages/ui/components/Toolbar.tsx, packages/ui/components/VisualEditor.tsx, packages/ui/components/VisualEditor/PropertyControls.tsx, packages/ui/components/VisualEditor/SchemaProperty.tsx, packages/ui/package.json, packages/ui/tsup.config.ts, packages/utils/package.json, packages/utils/src/class-names.ts, packages/utils/src/index.ts, packages/utils/tsconfig.json, packages/utils/tsup.config.ts, pnpm-lock.yaml
- Refactor the dropdown menu to make it more customizable for its users.
**Reasoning**: Tried to implement a multi-select dropdown menu, but the current implementation is too rigid to allow such an improvement.
- Add the `utils` package: The utils package currently contains only one method: `class-names` or in short `cn`. It is going to be used in at least 3 packages.
**[Reasoning](https://www.youtube.com/watch?v=tfgLd5ZSNPc)**
> blocked by https://github.com/asyncapi/.github/pull/300
=> Refactor DropdownMenu

.changeset/sweet-readers-itch.md, apps/studio-next/package.json, apps/studio/package.json, pnpm-lock.yaml
This PR updates `@asyncapi/parser` to version `3.2.2` in which [forceful normalization of YAML files to JSON format is removed](https://github.com/asyncapi/parser-js/pull/1044/files). That change allows `Parser` not to be misled anymore into thinking it's dealing with a JSON file instead of a YAML one, therefore paving the way for `Studio` to report correct `range` values in error diagnostics for YAML files.
Related to https://github.com/asyncapi/parser-js/issues/936, https://github.com/asyncapi/parser-js/issues/1012
=> fix: report correct `range` values in error diagnostics for YAML files

.changeset/popular-geese-rescue.md, apps/studio-next/package.json, apps/studio/package.json, pnpm-lock.yaml
This PR temporarily hard-locks the `@asyncapi/converter` on version `1.5.0`, to get the Studio up and running on production right now.
The permanent solution should be developed later.
Closes https://github.com/asyncapi/studio/issues/1138
=> fix: temporarily hard-lock `@asyncapi/converter` on `v1.5.0` as a hotfix (#1138)

.changeset/sour-waves-visit.md, README.md, apps/studio/Dockerfile, apps/studio/next.config.js, apps/studio/tsconfig.json
The Docker publish workflow has been broken since the migration to Next.js and/or PNPM, see https://github.com/asyncapi/studio/actions/workflows/publish-docker-image.yml.
This MR adapts the Dockerfile to be compatible with the new setup.
Discovered while trying to validate https://github.com/asyncapi/studio/pull/1150
⚒️ with ❤️ by [Siemens](https://opensource.siemens.com/)
=> fix(studio): fix Docker build

.changeset/honest-candles-brush.md, apps/studio/src/components/Modals/ConvertToLatestModal.tsx, apps/studio/src/services/index.ts, apps/studio/src/services/navigation.service.ts, apps/studio/src/services/preview.service.tsx, apps/studio/src/services/socket-client.service.tsx
This PR introduces the necessary changes for the implementation of  `readOnly` mode in studio when used with `asyncapi start preview` command.
Requirments:-
As the requirements of the implementation of this are following:-
- Starting of studio in it's minimal state when done through the to be implemented command `asyncapi start preview`.
- Other elements are disabled in this.
- Additon of websocket for syncing the  changes that come form file but not allowed to change anything from studio side.
These are also mentioned here https://github.com/asyncapi/cli/issues/1627#issuecomment-2730869866.
Approach:-
To achieve the above requirements I tried a few different approaches as below :-
1. As current implementation of readOnly requires the file to be served in from either URL …
=> feat: additional changes for implementation of new preview command

apps/studio/package.json
This pull request introduces the changes to update the `files` field in the `apps/studio/package.json` file to include only the necessary files and not the `cache` files in order to reduce the package size and bundle size.
Resolves #1193 
* Replaced the single entry `/build` with a comprehensive list of specific build files and subdirectories, such as `/build/server`, `/build/standalone`, and `/build/static`, among others. This provides finer-grained control over the included build artifacts.
Screenshots of package size taken up in `cli` by `studio`  after removing cache files.
=> fix: build cache ignored for smaller bundle size

.changeset/shiny-snails-cover.md, apps/studio/src/app/layout.tsx, apps/studio/src/components/Editor/ConvertDropdown.tsx, apps/studio/src/components/Editor/GenerateDropdown.tsx, apps/studio/src/components/Editor/ImportDropdown.tsx, apps/studio/src/components/Editor/SaveDropdown.tsx, apps/studio/src/components/Editor/ShareButton.tsx, apps/studio/src/components/SplitPane/Pane.tsx, apps/studio/src/components/Template/TemplateSidebar.tsx, apps/studio/src/components/Terminal/ProblemsTab.tsx, apps/studio/src/components/Terminal/TerminalInfo.tsx, apps/studio/src/components/Terminal/TerminalTabs.tsx, apps/studio/src/components/common/GoogleTagManager.tsx, apps/studio/src/helpers/analytics.ts
This PR adds Google Tags Manager (GTM) and the utility files to push event data to the GTM datalayer.    
Fixes #858
**PR Testing**
To test the PR one need to follow below steps: 
1. Create an account in [Google tags manager](https://tagmanager.google.com/) 
2. Create a container for the AsyncAPI studio
3. Copy the create GTM ID, it will be of format `GTM-XXXXXXX`
4. Create `.env` file into `apps/studio` and taste the below env variable thier
```
NEXT_PUBLIC_ANALYTICS_ID=GTM-XXXXXXX
```  
cc: @AayushSaini101
=> feat: add analytics

apps/studio/Dockerfile, apps/studio/next.config.js, apps/studio/src/app/page.tsx
The support for the `BASE_URL` environment variable introduced within https://github.com/asyncapi/studio/pull/248 was sadly broken when the project migrated to Next.JS.
This PR is composed of two commits:
1. The first commit fixes the permissions when copying the static assets for the Docker image (in particular, the `logo-studio.svg` was not loading, even when running without a `BASE_URL` - see below)
2. The second commit adds the `basePath` Next.JS config option as documented within [the official doc](https://nextjs.org/docs/app/api-reference/config/next-config-js/basePath).
Related to https://github.com/asyncapi/studio/issues/249
**logo-studio.svg not loading due to nginx file permissions**
**PR test**
I built locally the image and deployed it on …
=> fix: support BASE_URL for studio docker builds
